FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN corepack enable
RUN yarn install

RUN yarn nx build sniply-app

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/sniply-app .

EXPOSE 4201

CMD ["node", "server/server.mjs"]