FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN corepack enable
RUN yarn install

RUN yarn nx build sniply-website

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/sniply-website .

EXPOSE 4200

CMD ["node", "server/server.mjs"]