FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

RUN corepack enable
RUN yarn install

RUN yarn nx build sniply-server

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/dist/apps/sniply-server .

RUN npm install --omit=dev --ignore-scripts
# patch for a packaging gap
RUN npm install --no-save --ignore-scripts pg@8.18.0

EXPOSE 3000

CMD ["node", "main.js"]