apiVersion: v1
kind: Service
metadata:
  name: sniply-server
  namespace: sniply-staging

spec:
  selector:
    app: sniply-server

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP